<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2014-05-08 22:57:12
 * @@Modify Date: 2015-07-21 17:13:22
 * @@Function:
 */
 ?>
<?php
	$info = $this->getRequest()->getParam('info');
	if(isset($info['timer']) && $info['timer']){
		echo $this->getChildHtml('shopbrand_grid_timer');
	} else {
		echo $this->getChildHtml('shopbrand_grid');
	}
?>
